### PR TITLE
Update version and Add spells

### PR DESCRIPTION
**Pull request by backcho**

### CODE REVIEW

**Comment by dazer** [comment]
I think these two, being self heals, should be entered like this, rather than targeted at the 4th unit
[373]={type="nuke", damageATK=100, target=1, selfhealATK=100},
[374]={type="nuke", damageATK=100, target=1, selfhealATK=40},

**Comment by FlipperPA** [comment]
Can we get these changes merged in, @hythloday? Thanks!

**Comment by majtymit** [comment]
bump

**Review by dave128 — APPROVED** [review]

**Comment by FlipperPA** [comment]
@dave128 Do you have permissions to merge this?

**Comment by dwhelan-rv** [comment]
> @dave128 Do you have permissions to merge this?

nope: 
image

**Comment by NoleHealth** [comment]
Thanks @dave128 !!

**Comment by dwhelan-rv** [comment]
FWIW - to anyone waiting for this to get merged to update your addon, you can simply copy the entire contents of https://raw.githubusercontent.com/hythloday/VenturePlanSoDMissions/4cacc0bef42c03edc9c4546677043291aef00385/extra-vs-spells.lua into the file of the same name in your `VenturePlan` folder.  Make sure to overwrite the entire files contents.  Otherwise just download the file and replace `extra-vs-spells.lua` file with the one you downloaded.

**Pull request closed without merging**
